apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-api
    name: vote
  name: vote
  namespace: emojivote
spec:
  ports:
  - name: cce-service-0
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: vote-api
    version: v1
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: emoji-api
    name: emoji
  name: emoji
  namespace: emojivote
spec:
  ports:
  - name: cce-service-0
    port: 50050
    protocol: TCP
    targetPort: 50050
  selector:
    app: emoji-api
    version: v1
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-api
    name: vote-rest
  name: vote-rest
  namespace: emojivote
spec:
  ports:
  - name: vote-api-rest
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: vote-api
    version: v1
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: emoji-api
    name: emoji-rest
  name: emoji-rest
  namespace: emojivote
spec:
  ports:
  - name: emoji-api-rest
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: emoji-api
    version: v1
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-emoji
    name: emoji-web
  name: emoji-web
  namespace: emojivote
spec:
  ports:
  - name: emoji-web-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-emojivote
    version: v1
  sessionAffinity: None
  type: ClusterIP
