apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-api
    name: vote
  name: vote
  namespace: emojivote
spec:
  ports:
  - name: cce-service-0
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: vote-api
    version: v1
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: emoji-api
    name: emoji
  name: emoji
  namespace: emojivote
spec:
  ports:
  - name: cce-service-0
    port: 50050
    protocol: TCP
    targetPort: 50050
  selector:
    app: emoji-api
    version: v1
  sessionAffinity: None
  type: ClusterIP
