apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/elb.port: "80"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
  labels:
    isExternal: "true"
    zone: data
  name: demo-web
  namespace: emojivote
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: emoji-web
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
        property:
          ingress.beta.kubernetes.io/url-match-mode: STARTS_WITH
